name: CI

on:
  push:
    branches:
    - main
    - release/*
    
  pull_request:
    branches: 
    - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubunto-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run a oneline script
        run: echo Hello, world!

      - name: run multiline script
        run: |
          echo Add other actions to build
          echo test and deploy you work
    
